// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

// Generated by chainlink-ccip-skill (Cap 5 eval) — VERBATIM from chainlink-local.md.
import {Test} from "forge-std/Test.sol";
import {CCIPLocalSimulator, IRouterClient, LinkToken, BurnMintERC677Helper} from
    "@chainlink/local/src/ccip/CCIPLocalSimulator.sol";
// Eval-adjusted: skill's example used @chainlink/contracts-ccip/contracts/... which collides with
// this repo's 1.5 pin. Use chainlink-local's bundled 1.6 Client to match the simulator's router.
import {Client} from "@ccip-local-contracts/libraries/Client.sol";

contract CCIPLocalTest is Test {
    CCIPLocalSimulator public ccipLocalSimulator;
    uint64 public destinationChainSelector;
    IRouterClient public router;
    LinkToken public linkToken;
    BurnMintERC677Helper public ccipBnMToken;

    address alice;
    address bob;

    function setUp() public {
        ccipLocalSimulator = new CCIPLocalSimulator();

        (
            uint64 chainSelector,
            IRouterClient sourceRouter,
            ,
            ,
            LinkToken link,
            BurnMintERC677Helper ccipBnM,
        ) = ccipLocalSimulator.configuration();

        destinationChainSelector = chainSelector;
        router = sourceRouter;
        linkToken = link;
        ccipBnMToken = ccipBnM;

        alice = makeAddr("alice");
        bob = makeAddr("bob");
    }

    function test_transferTokensPayFeesInLink() public {
        ccipBnMToken.drip(alice);
        uint256 amountToSend = 100;

        uint256 balanceOfAliceBefore = ccipBnMToken.balanceOf(alice);
        uint256 balanceOfBobBefore = ccipBnMToken.balanceOf(bob);

        vm.startPrank(alice);
        ccipLocalSimulator.requestLinkFromFaucet(alice, 5 ether);

        ccipBnMToken.approve(address(router), amountToSend);

        Client.EVMTokenAmount[] memory tokensToSend = new Client.EVMTokenAmount[](1);
        tokensToSend[0] = Client.EVMTokenAmount({token: address(ccipBnMToken), amount: amountToSend});

        Client.EVM2AnyMessage memory message = Client.EVM2AnyMessage({
            receiver: abi.encode(bob),
            data: "",
            tokenAmounts: tokensToSend,
            extraArgs: Client._argsToBytes(Client.EVMExtraArgsV1({gasLimit: 0})),
            feeToken: address(linkToken)
        });

        uint256 fees = router.getFee(destinationChainSelector, message);
        linkToken.approve(address(router), fees);
        router.ccipSend(destinationChainSelector, message);

        vm.stopPrank();

        assertEq(ccipBnMToken.balanceOf(alice), balanceOfAliceBefore - amountToSend);
        assertEq(ccipBnMToken.balanceOf(bob), balanceOfBobBefore + amountToSend);
    }
}
